apps/web/lib/web/router.ex
defmodule Web.Router do
  use Web, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:put_root_layout, {Web.LayoutView, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(Web.Plugs.SetLocale, "en")
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :fdsn do
    plug(:accepts, ["json", "text", "xml"])
  end

  scope "/", Web do
    pipe_through(:browser)
  end

  scope "/api/v1", Web.API.V1 do
    pipe_through(:api)

    get("/events", EventController, :index)
    get("/events/types", EventController, :types)
    get("/events/:event_publicid", EventController, :show)
    get("/events/:event_publicid/cities", EventController, :cities)
    get("/events/:event_publicid/past-seismicity", EventController, :past_seismicity)
    get("/events/:event_publicid/phases", EventController, :phases)
    # get("/events/:event_publicid/intensities", EventController, :intensities)
    # get("/events/:event_publicid/testimonies", EventController, :testimonies)

    get("/zones", ZoneController, :index)
    get("/zones/:zone_slug", ZoneController, :show)

    get("/zones/:zone_slug/stations", ZoneController, :stations)

    get("/stations", StationController, :index)

    get("/surveys/forms", SurveyController, :forms)
    get("/surveys/forms/:id", SurveyController, :form)

    get("/surveys/cities/:key", SurveyController, :city_survey)
    # put("/surveys/cities/:key", SurveyController, :update_city_survey)

    # get("/testimonies", TestimonyController, :testimonies)
    post("/testimonies", TestimonyController, :new)
    get("/testimonies/:key", TestimonyController, :testimony)
    put("/testimonies/:key", TestimonyController, :update)
    get("/testimonies/:key/answers", TestimonyController, :answers)
    post("/testimonies/:key/answers", TestimonyController, :update_answer)
    put("/testimonies/:key/answers", TestimonyController, :update_answer)

    get("/cities", GeographyController, :cities)
    get("/streets", GeographyController, :streets)
  end

  scope "/fdsnws/event", Web do
    pipe_through(:fdsn)

    get("/", FDSNEventController, :base)
    get("/1/", FDSNEventController, :base)
    get("/1/query", FDSNEventController, :query)
    get("/1/application.wadl", FDSNEventController, :wadl)
    get("/1/catalogs", FDSNEventController, :catalogs)
    get("/1/contributors", FDSNEventController, :contributors)
    get("/1/version", FDSNEventController, :version)
  end

  scope "/:locale", Web do
    pipe_through(:browser)

    get("/search", EventController, :search)
    get("/search/results", EventController, :search_results)
  end
end

apps/web/lib/web/controllers/api/v1/event_controller.ex
defmodule Web.API.V1.EventController do
  use Web, :controller

  alias Namazu.Helpers
  alias Namazu.Cache

  def cities(conn, _params = %{"event_publicid" => event_publicid}) do
    cities =
      Cache.get_distintive_cities(event_publicid)
      |> Enum.map(&Helpers.to_feature(&1))
      |> Helpers.geojson()

    json(conn, cities)
  end

  def past_seismicity(conn, _params = %{"event_publicid" => event_publicid}) do
    events =
      Cache.get_past_seismicity(event_publicid)
      |> Enum.map(&Helpers.to_feature(&1))
      |> Helpers.geojson()

    json(conn, events)
  end

  def format_phase(phase) do
    %{
      arrivalID: phase.id,
      originID: phase.origin_id,
      pickID: phase.pick.id,
      networkCode: phase.pick.stream.network_code,
      stationCode: phase.pick.stream.station_code,
      locationCode: phase.pick.stream.location_code,
      channelCode: phase.pick.stream.channel_code,
      azimuth: phase.azimuth,
      distance: phase.distance,
      phaseCode: phase.phase_code,
      time: phase.pick.time,
      timeResidual: phase.time_residual,
      automatic: phase.pick.automatic
    }
  end

  def phases(conn, _params = %{"event_publicid" => event_publicid}) do
    phases =
      Cache.get_preferred_origin_phases(event_publicid)
      |> Enum.map(&Web.API.V1.EventController.format_phase(&1))

    json(conn, phases)
  end

  def types(conn, _params) do
    types =
      Cache.get_event_types()
      |> Enum.map(fn type ->
        %{name: type.event_type, count: type.count}
      end)

    json(conn, types)
  end

  def format_origin(origin) do
    %{
      id: origin.id,
      eventID: origin.event_id,
      eventPreferred: origin.event_preferred,
      time: origin.time,
      timeUncertainty: origin.time_uncertainty,
      timeConfidenceLevel: origin.time_confidence_level,
      latitude: origin.latitude,
      latitudeUncertainty: origin.latitude_uncertainty,
      latitudeConfidenceLevel: origin.latitude_confidence_level,
      longitude: origin.longitude,
      longitudeUncertainty: origin.longitude_uncertainty,
      longitudeConfidenceLevel: origin.longitude_confidence_level,
      depth: origin.depth,
      depthUncertainty: origin.depth_uncertainty,
      depthUsed: origin.depth_used,
      depthType: origin.depth_type,
      methodID: origin.method_id,
      earthmodelID: origin.earthmodel_id,
      automatic: origin.automatic,
      evaluationStatus: origin.evaluation_status,
      originType: origin.origin_type,
      agency: origin.agency,
      author: origin.author,
      createdAt: origin.created_at,
      insertedAt: origin.inserted_at,
      updatedAt: origin.updated_at
    }
  end

  def format_magnitude(magnitude) do
    %{
      id: magnitude.id,
      eventID: magnitude.event_id,
      originID: magnitude.origin_id,
      eventPreferred: magnitude.event_preferred,
      magnitude: magnitude.magnitude,
      magnitudeUncertainty: magnitude.magnitude_uncertainty,
      magnitudeType: magnitude.magnitude_type,
      methodID: magnitude.method_id,
      stationCount: magnitude.station_count,
      evaluationStatus: magnitude.evaluation_status,
      agency: magnitude.agency,
      author: magnitude.author,
      createdAt: magnitude.created_at,
      insertedAt: magnitude.inserted_at,
      updatedAt: magnitude.updated_at
    }
  end

  def format_event(event) do
    %{
      id: event.id,
      zoneID: event.zone_id,
      publicid: event.publicid,
      eventType: event.event_type,
      localtime: event.localtime,
      timezone: event.timezone,
      felt: event.felt,
      preferredOrigin: format_origin(event.preferred_origin),
      preferredMagnitude: format_magnitude(event.preferred_magnitude),
      insertedAt: event.inserted_at,
      updatedAt: event.updated_at
    }
  end

  def show(conn, _params = %{"event_publicid" => event_publicid}) do
    event =
      Cache.get_event(event_publicid)
      |> format_event()

    json(conn, event)
  end

  def index(conn, params) do
    search = %Namazu.Search.EventSearch{
      start_time: params["start_time"],
      end_time: params["end_time"],
      minimal_longitude: Helpers.parse_float(params["minimal_longitude"]),
      maximal_longitude: Helpers.parse_float(params["maximal_longitude"]),
      minimal_latitude: Helpers.parse_float(params["minimal_latitude"]),
      maximal_latitude: Helpers.parse_float(params["maximal_latitude"]),
      minimal_magnitude: Helpers.parse_float(params["minimal_magnitude"]),
      maximal_magnitude: Helpers.parse_float(params["maximal_magnitude"]),
      minimal_depth: Helpers.parse_float(params["minimal_depth"]),
      maximal_depth: Helpers.parse_float(params["maximal_depth"]),
      event_types: String.split(params["event_types"], ","),
      limit: Helpers.parse_integer(params["limit"]),
      offset: Helpers.parse_integer(params["offset"]),
      order_by: Helpers.parse_order_by(params["order_by"])
    }

    events =
      Namazu.Search.EventSearch.query(search)
      |> Namazu.Repo.all()
      |> Enum.map(&Helpers.to_feature(&1))
      |> Helpers.geojson()

    json(conn, events)
  end
end

apps/web/lib/web/controllers/event_controller.ex
defmodule Web.EventController do
  import Plug.Conn

  use Web, :controller

  require Namazu.Gettext

  import Namazu.Helpers,
    only: [
      parse_datetime: 1,
      parse_integer: 1,
      parse_order_by: 1
    ]

  alias Namazu.Repo
  alias Namazu.Seismic
  alias Namazu.Cache

  import Ecto.Query

  def fdsn_query_path(event_search, format \\ nil) do
    params = Namazu.Search.EventSearch.fdsn_query_params(event_search)

    params =
      if format do
        Map.put(params, "format", format)
      else
        params
      end
      |> Enum.map(fn {key, value} -> {key, "#{value}"} end)
      |> Enum.into(%{})

    Web.Router.Helpers.fdsn_event_path(Web.Endpoint, :query, params)
  end

  def search(conn, _params = %{"locale" => locale}) do
    event_types =
      Cache.get_event_types()
      |> Enum.filter(fn t -> t.event_type not in ["not existing", "not locatable"] end)

    title = Gettext.gettext(Namazu.Gettext, "Search")

    render(conn, "search.html", title: title, locale: locale, event_types: event_types)
  end

  def convert_start_date(start_date) do
    case start_date do
      "" -> nil
      nil -> nil
      start_date -> "#{start_date}T00:00:00Z" |> parse_datetime()
    end
  end

  def convert_end_date(end_date) do
    case end_date do
      "" -> nil
      nil -> nil
      end_date -> "#{end_date}T23:59:59.999999Z" |> parse_datetime()
    end
  end

  def search_results(conn, params = %{"locale" => locale}) do
    events_limit = 30
    query_params = Map.get(conn, :query_params)

    event_types =
      query_params
      |> Enum.filter(fn {key, value} ->
        String.starts_with?(key, "event_type_") and value == "true"
      end)
      |> Enum.map(fn {key, _value} -> String.slice(key, 11, 40) end)

    event_publicid =
      case Map.get(query_params, "event_id") do
        "" -> nil
        event_publicid -> event_publicid
      end

    search_params = %Namazu.Search.EventSearch{
      start_time: Map.get(query_params, "start_date") |> convert_start_date(),
      end_time: Map.get(query_params, "end_date") |> convert_end_date(),
      minimal_longitude:
        Map.get(query_params, "minimal_longitude") |> Namazu.Helpers.parse_float(),
      maximal_longitude:
        Map.get(query_params, "maximal_longitude") |> Namazu.Helpers.parse_float(),
      minimal_latitude: Map.get(query_params, "minimal_latitude") |> Namazu.Helpers.parse_float(),
      maximal_latitude: Map.get(query_params, "maximal_latitude") |> Namazu.Helpers.parse_float(),
      minimal_magnitude:
        Map.get(query_params, "minimal_magnitude") |> Namazu.Helpers.parse_float(),
      maximal_magnitude:
        Map.get(query_params, "maximal_magnitude") |> Namazu.Helpers.parse_float(),
      minimal_depth: Map.get(query_params, "minimal_depth") |> Namazu.Helpers.parse_float(),
      maximal_depth: Map.get(query_params, "maximal_depth") |> Namazu.Helpers.parse_float(),
      latitude: Map.get(query_params, "latitude") |> Namazu.Helpers.parse_float(),
      longitude: Map.get(query_params, "longitude") |> Namazu.Helpers.parse_float(),
      maximal_radius: Map.get(query_params, "maximal_radius") |> Namazu.Helpers.parse_float(),
      event_publicid: event_publicid,
      event_types: event_types,
      limit: Map.get(query_params, "limit") |> parse_integer(),
      offset: Map.get(query_params, "offset") |> parse_integer(),
      order_by: Map.get(query_params, "order_by") |> parse_order_by()
    }

    search_query = Namazu.Search.EventSearch.query(search_params)

    fdsn_xml_path = fdsn_query_path(search_params)

    geojson_path = fdsn_query_path(search_params, "json")

    fdsn_text_path = fdsn_query_path(search_params, "text")

    events_count = search_query |> Repo.aggregate(:count, :id)

    current_page = Map.get(params, "page", "1") |> String.to_integer()

    offset = events_limit * (current_page - 1)

    events =
      search_query
      |> Seismic.preload_distinctive_cities()
      |> offset(^offset)
      |> limit(^events_limit)
      |> Repo.all()

    title = Gettext.gettext(Namazu.Gettext, "Search results")

    event_uri_prefix = "event_uri_prefix_#{String.downcase(locale)}" |> Namazu.get_parameter()

    render(conn, "search_results.html",
      locale: locale,
      title: title,
      event_uri_domain: Namazu.get_parameter("event_uri_domain"),
      event_uri_prefix: event_uri_prefix,
      events_count: events_count,
      events_limit: events_limit,
      events: events,
      fdsn_xml_path: fdsn_xml_path,
      geojson_path: geojson_path,
      fdsn_text_path: fdsn_text_path
    )
  end
end

apps/web/lib/web/views/event_view.ex
defmodule Web.EventView do
  use Web, :view

  import Web.Filters
  import Namazu.Helpers
end

apps/web/lib/web/templates/event/events_table.html.eex
<div>
<table class="table-auto w-full text-xs">
  <thead class="pb-2 mb-2">
    <tr>
      <th><%= gettext "Universal datetime" %></th>
      <th><%= gettext "Local datetime" %></th>
      <th>Magnitude</th>
      <th><%= gettext "Country" %></th>
    </tr>
  </thead>
  <tbody class="text-base">
    <%= for event <- @events do %>
    <tr>
      <td class="text-center"><%= format_date(event.preferred_origin.time, @locale) %> <%= format_time(event.preferred_origin.time, false) %></td>
      <td class="text-center"><%= format_date(event.localtime, @locale) %> <%= format_time(event.localtime, false) %></td>
      <td class="text-center">
        <a href="https://<%= @domain %><%= @event_uri_prefix %>/<%= event.publicid %>" target="_blank">
          <strong><%= event.preferred_magnitude.magnitude |> format_magnitude %></strong>
        </a>
      </td>
      <td>
        <%= country_flag(@conn, event.distinctive_city.country_iso2) %>
        <span class="align-middle"><%= event.distinctive_city.name %></span>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
<div class="flex justify-between mt-4 mb-4">
  <div>
  <%= if @previous_link do %>
  <a class="button border-2 bg-neutral-50 hover:bg-neutral-100 border-sky-600 text-sky-600 text-sm w-1/3" href="<%= @previous_link %>"><%= @previous_label %></a>
  <% end %>
  </div>
  <div>
  <%= if @next_link do %>
  <a class="self-end button border-2 bg-neutral-50 hover:bg-neutral-100 border-sky-600 text-sky-600 text-sm w-1/3" href="<%= @next_link %>"><%= @next_label %></a>
  <% end %>
  </div>
</div>

apps/web/lib/web/templates/event/search.html.eex
<%= form_for @conn, Routes.event_path(@conn, :search_results, @locale), [method: :get], fn form -> %>
<section class="p-8">
  <div class="container mx-auto">
    <div class="columns-md gap-8 space-y-8">
      <div class="input-group">
        <label class="input-label"><%= gettext("Start date") %></label>
        <%= date_input(form, :start_date, class: "input-namazu") %>
        <label class="input-label"><%= gettext("End date") %></label>
        <%= date_input(form, :end_date, class: "input-namazu") %>
      </div>
      <div class="input-group">
        <div class="w-full flex justify-center">
          <div class="md:max-w-[33%]">
            <label class="input-label"><%= gettext("Maximal latitude") %></label>
            <%= number_input(form, :maximal_latitude, class: "input-namazu", step: 0.01) %>
          </div>
        </div>
        <div class="w-full flex justify-between">
          <div class="md:max-w-[33%]">
            <label class="input-label"><%= gettext("Minimal longitude") %></label>
            <%= number_input(form, :minimal_longitude, class: "input-namazu", step: 0.01) %>
          </div>
          <div class="md:max-w-[33%]">
            <label class="input-label"><%= gettext("Maximal longitude") %></label>
            <%= number_input(form, :maximal_longitude, class: "input-namazu", step: 0.01) %>
          </div>
        </div>
        <div class="w-full flex justify-center">
          <div class="md:max-w-[33%]">
            <label class="input-label"><%= gettext("Minimal latitude") %></label>
            <%= number_input(form, :minimal_latitude, class: "input-namazu", step: 0.01) %>
          </div>
        </div>
      </div>
      <div class="input-group">
        <label class="input-label"><%= gettext("Minimal magnitude") %></label>
        <%= number_input(form, :minimal_magnitude, class: "input-namazu", step: 0.1) %>
        <label class="input-label"><%= gettext("Maximal magnitude") %></label>
        <%= number_input(form, :maximal_magnitude, class: "input-namazu", step: 0.1) %>
      </div>
      <div class="input-group">
        <label class="input-label"><%= gettext("Minimal depth") %></label>
        <%= number_input(form, :minimal_depth, class: "input-namazu") %>
        <label class="input-label"><%= gettext("Maximal depth") %></label>
        <%= number_input(form, :maximal_depth, class: "input-namazu") %>
      </div>
      <div class="input-group">
        <label class="input-label"><%= gettext("Event ID") %></label>
        <%= text_input(form, :event_id, class: "input-namazu") %>
      </div>
      <div class="input-group">
        <label class="input-label"><%= gettext("Maximal radius (in degrees)") %></label>
        <%= number_input(form, :maximal_radius, class: "input-namazu", step: 0.01) %>
        <label class="input-label"><%= gettext("Latitude center") %></label>
        <%= number_input(form, :latitude, class: "input-namazu", step: 0.01) %>
        <label class="input-label"><%= gettext("Longitude center") %></label>
        <%= number_input(form, :longitude, class: "input-namazu", step: 0.01) %>
      </div>
      <div class="input-group">
        <label class="input-label"><%= gettext("Limit") %></label>
        <%= number_input(form, :limit, class: "input-namazu") %>
        <label class="input-label"><%= gettext("Offset") %></label>
        <%= number_input(form, :offset, class: "input-namazu") %>
        <label class="input-label"><%= gettext("Order by") %></label>
        <%= select(form, :order_by, [
              [key: gettext("Descending time"), value: :descending_time],
              [key: gettext("Ascending time"), value: :ascending_time],
              [key: gettext("Descending magnitude"), value: :descending_magnitude],
              [key: gettext("Ascending magnitude"), value: :ascending_magnitude]
            ], class: "input-namazu") %>
      </div>
      <div class="input-group">
        <label class="input-label"><%= gettext("Event types") %></label>
        <%= for event_type <- @event_types do %>
          <% translated_event_type = Gettext.dgettext(Namazu.Gettext, "event_types", event_type.event_type) |> String.capitalize() %>
          <label class="checkbox-label">
            <%= checkbox(form, "event_type_#{event_type.event_type}" |> String.to_atom(), class: "checkbox-namazu") %>
            &nbsp;<%= translated_event_type %>
            <span class="tag"><%= event_type.count %></span>
          </label>
          </p>
        <% end %>
      </div>
    </div>
    <div class="mt-8 gap-4 flex justify-evenly">
      <input type="reset" class="button border-2 bg-neutral-50 hover:bg-neutral-100 border-sky-600 text-sky-600" value="<%= gettext("Reset") %>">
      <button type="submit" class="button bg-sky-600 hover:bg-sky-700 text-neutral-50"><%= gettext "Search" %></button>
    </div>
  </div>
</section>
<% end %>

apps/web/lib/web/templates/event/search_results.html.eex
<section class="p-8">
  <div class="container mx-auto">
    <%= if @events_count > 0 do %>
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
      <div class="text-lg space-y-8">
        <div class="group p-8 text-justify">
          <div class="mb-8">
            <%= ngettext "You search returns one event.", "Your search returns %{events_count} events.", @events_count, events_count: @events_count %>
            <%= gettext "You can download your search result using one of the following formats :" %>
          </div>
          <div class="grid grid-cols-2 divide-x-2">
            <div class="p-3 m-3">
              <div class="grow">
                <span class="font-bold pb-3 block"><%= gettext "FDSN-Event webservice" %></span>
                  <p><%= gettext "XML standard developped by the research community." %></p>
                  <p><%= gettext "Researchers looking for the maximum information should use this format as it contains almost every event parameters." %></p>
                  <p>
                  <%= gettext("QuakeML documentation is available on the %{link}.", link: safe_to_string(link(gettext("FDSN website"), to: "https://www.fdsn.org/webservices/fdsnws-event-1.2.pdf"))) |> raw() %>
                  </p>
              </div>
              <div class="pt-2">
                <a class="block text-center button bg-sky-600 hover:bg-sky-700 text-neutral-50 m-2 text-sm" href="<%= @fdsn_text_path %>" download="events.txt"><%= gettext "Download Text" %></a>
                <a class="block text-center button bg-sky-600 hover:bg-sky-700 text-neutral-50 m-2 text-sm" href="<%= @fdsn_xml_path %>" download="events.xml"><%= gettext "Download QuakeML" %></a>
              </div>
            </div>
            <div class="flex flex-col p-3 m-3">
              <div class="grow">
                <span class="font-bold pb-3 block">GeoJSON</span>
                <p><%= gettext "JSON standard that can be easily parsed by developpers." %></p>
                <p><%= gettext("You can also easily open the link in GIS software like %{qgis_link}.", qgis_link: safe_to_string(link("QGIS", to: "https://www      .qgis.org"))) |> raw() %></p>
              </div>
              <div>
                <a class="align-bottom block text-center button bg-sky-600 hover:bg-sky-700 text-neutral-50 m-2 text-sm" href="<%= @geojson_path %>" download="events.json"><%= gettext "Download GeoJSON" %></a>
              </div>
            </div>
          </div>
          <div class="border-2 rounded-lg bg-grey-400 flex">
            <div class="m-2">
              <img src="<%= Routes.static_path(@conn, "/images/creative-commons-by.svg" ) %>" />
            </div>
            <div class="text-center text-sm m-auto">
              <span><%= gettext "The seismicity catalog data is freely available under a CC BY 4.0 license." %></span>
            </div>
          </div>
        </div>
      </div>
      <div class="group text-lg">
        <%= events_table(@conn, @locale, @events, @events_count, @events_limit, @event_uri_domain, @event_uri_prefix, gettext("Previous page"), gettext("Next page")) %>
      </div>
    </div>
    <% else %>
      <%= gettext "Your search returns no event." %>
    <% end %>
  </div>
</section>