apps/web/lib/web/router.ex
defmodule Web.Router do
  use Web, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:put_root_layout, {Web.LayoutView, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(Web.Plugs.SetLocale, "en")
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :fdsn do
    plug(:accepts, ["json", "text", "xml"])
  end

  scope "/", Web do
    pipe_through(:browser)
  end

  scope "/api/v1", Web.API.V1 do
    pipe_through(:api)

    get("/events", EventController, :index)
    get("/events/types", EventController, :types)
    get("/events/:event_publicid", EventController, :show)
    get("/events/:event_publicid/cities", EventController, :cities)
    get("/events/:event_publicid/past-seismicity", EventController, :past_seismicity)
    get("/events/:event_publicid/phases", EventController, :phases)
    # get("/events/:event_publicid/intensities", EventController, :intensities)
    # get("/events/:event_publicid/testimonies", EventController, :testimonies)

    get("/zones", ZoneController, :index)
    get("/zones/:zone_slug", ZoneController, :show)

    get("/zones/:zone_slug/stations", ZoneController, :stations)

    get("/stations", StationController, :index)

    get("/surveys/forms", SurveyController, :forms)
    get("/surveys/forms/:id", SurveyController, :form)

    get("/surveys/cities/:key", SurveyController, :city_survey)
    # put("/surveys/cities/:key", SurveyController, :update_city_survey)

    # get("/testimonies", TestimonyController, :testimonies)
    post("/testimonies", TestimonyController, :new)
    get("/testimonies/:key", TestimonyController, :testimony)
    put("/testimonies/:key", TestimonyController, :update)
    get("/testimonies/:key/answers", TestimonyController, :answers)
    post("/testimonies/:key/answers", TestimonyController, :update_answer)
    put("/testimonies/:key/answers", TestimonyController, :update_answer)

    get("/cities", GeographyController, :cities)
    get("/streets", GeographyController, :streets)
  end

  scope "/fdsnws/event", Web do
    pipe_through(:fdsn)

    get("/", FDSNEventController, :base)
    get("/1/", FDSNEventController, :base)
    get("/1/query", FDSNEventController, :query)
    get("/1/application.wadl", FDSNEventController, :wadl)
    get("/1/catalogs", FDSNEventController, :catalogs)
    get("/1/contributors", FDSNEventController, :contributors)
    get("/1/version", FDSNEventController, :version)
  end

  scope "/:locale", Web do
    pipe_through(:browser)

    get("/search", EventController, :search)
    get("/search/results", EventController, :search_results)
  end
end

apps/web/lib/web/controllers/fdsn_event_controller.ex
defmodule Web.FDSNEventController do
  import Plug.Conn

  alias Namazu.Seismic
  alias Namazu.Repo
  import Ecto.Query
  alias Namazu.Helpers
  alias Namazu.Cache

  use Web, :controller

  @version 1.2

  # "catalog",
  # "contributor",

  def trim_xml(xml) do
    xml
    |> String.split("\n")
    |> Enum.map_join(&String.trim/1)

    # |> Enum.join()
  end

  def parse_event_types(_event_types = ""), do: nil
  def parse_event_types(_event_types = nil), do: nil

  def parse_event_types(event_types) do
    String.split(event_types, ",")
    |> Enum.map(&Namazu.Seismic.Event.quakeml_to_namazu_event_type(&1))
  end

  def fdsn_event_query(params) do
    Namazu.Search.EventSearch.query(%Namazu.Search.EventSearch{
      start_time: Map.get(params, "starttime") |> Helpers.parse_datetime(),
      end_time: Map.get(params, "endtime") |> Helpers.parse_datetime(),
      minimal_longitude: Map.get(params, "minlongitude") |> Helpers.parse_float(),
      maximal_longitude: Map.get(params, "maxlongitude") |> Helpers.parse_float(),
      minimal_latitude: Map.get(params, "minlatitude") |> Helpers.parse_float(),
      maximal_latitude: Map.get(params, "maxlatitude") |> Helpers.parse_float(),
      minimal_magnitude: Map.get(params, "minmagnitude") |> Helpers.parse_float(),
      maximal_magnitude: Map.get(params, "maxmagnitude") |> Helpers.parse_float(),
      minimal_depth: Map.get(params, "mindepth") |> Helpers.parse_float(),
      maximal_depth: Map.get(params, "maxdepth") |> Helpers.parse_float(),
      latitude: Map.get(params, "latitude") |> Helpers.parse_float(),
      longitude: Map.get(params, "longitude") |> Helpers.parse_float(),
      maximal_radius: Map.get(params, "maxradius") |> Helpers.parse_float(),
      event_types: Map.get(params, "eventtype") |> parse_event_types(),
      event_publicid: Map.get(params, "eventid"),
      limit: Map.get(params, "limit") |> Helpers.parse_integer(),
      offset: Map.get(params, "offset") |> Helpers.parse_integer(),
      order_by: Map.get(params, "orderby") |> Helpers.parse_order_by(),
      updated_after: Map.get(params, "updatedafter") |> Helpers.parse_datetime()
    })
  end

  def get_event_ids_chunks(params, chunk_size \\ 100) do
    fdsn_event_query(params)
    |> Repo.all()
    |> Enum.map(fn e -> e.id end)
    |> Enum.chunk_every(chunk_size)
  end

  def get_events_from_ids(event_ids) do
    Seismic.event_query()
    |> where([event: e], e.id in ^event_ids)
  end

  # Could be replace in Elixir 1.10 with
  # Enum.sort_by(events, & &1.preferred_origin.time, DateTime)
  def compare_datetime(d1, d2) do
    case DateTime.compare(d1, d2) do
      :lt -> true
      :eq -> true
      :gt -> false
    end
  end

  def sort_events_chunk(events, params) do
    case Map.get(params, "orderby") do
      "time" ->
        Enum.sort_by(events, & &1.preferred_origin.time, fn d1, d2 ->
          not compare_datetime(d1, d2)
        end)

      "time-asc" ->
        Enum.sort_by(events, & &1.preferred_origin.time, &compare_datetime(&1, &2))

      # events |> Enum.sort_by(fn e -> e.preferred_origin.time end, DateTime)

      "magnitude" ->
        events |> Enum.sort_by(fn e -> e.preferred_magnitude.magnitude end) |> Enum.reverse()

      "magnitude-asc" ->
        events |> Enum.sort_by(fn e -> e.preferred_magnitude.magnitude end)

      _ ->
        events
    end
  end

  def query(conn, params) do
    format = Map.get(params, "format", "xml")
    params = Map.put_new(params, "orderby", "time")
    event_uri_prefix = Namazu.get_parameter("event_uri_prefix_en")
    event_uri_prefix_fr = Namazu.get_parameter("event_uri_prefix_fr")
    event_uri_domain = Namazu.get_parameter("event_uri_domain")

    case format do
      "json" ->
        features =
          fdsn_event_query(params)
          |> Seismic.preload_distinctive_cities()
          |> Repo.all()
          |> Enum.map(fn e ->
            %{
              id: e.publicid,
              geometry: %{
                coordinates: [
                  e.preferred_origin.longitude,
                  e.preferred_origin.latitude,
                  -e.preferred_origin.depth
                ],
                type: "Point"
              },
              properties: %{
                longitude: e.preferred_origin.longitude,
                latitude: e.preferred_origin.latitude,
                depth: e.preferred_origin.depth,
                description: %{
                  en: Helpers.event_description(e),
                  fr:
                    Gettext.with_locale(Namazu.Gettext, "fr", fn ->
                      Helpers.event_description(e)
                    end)
                },
                automatic: e.preferred_origin.automatic,
                mag: e.preferred_magnitude.magnitude,
                magType: e.preferred_magnitude.magnitude_type,
                # place: "TODO!!!",
                time: e.preferred_origin.time,
                type: e.event_type,
                url: %{
                  en: "https://#{event_uri_domain}#{event_uri_prefix}/#{e.publicid}",
                  fr: "https://#{event_uri_domain}#{event_uri_prefix_fr}/#{e.publicid}"
                }
              },
              type: "Feature"
            }
          end)

        json(conn, %{
          type: "FeatureCollection",
          features: features
        })

      "text" ->
        conn =
          conn
          |> put_resp_content_type("text/plain")
          |> send_chunked(:ok)

        chunk(
          conn,
          "# EventID | Time | Latitude | Longitude | Depth/km | Author | Catalog | Contributor | ContributorID | MagnitudeType | Magnitude | MagnitudeAuthor | EventLocationName | EventType\n"
        )

        for chunk <- get_event_ids_chunks(params) do
          events =
            get_events_from_ids(chunk)
            |> Seismic.preload_preferred()
            |> Seismic.preload_distinctive_cities()
            |> Seismic.preload_zone()
            |> Repo.all()
            |> sort_events_chunk(params)

          text =
            Phoenix.View.render(Web.FDSNEventView, "query.txt", events: events)
            |> String.trim_leading()

          chunk(conn, text)
        end

        conn

      _ ->
        include_all_origins = Map.get(params, "includeallorigins", "false") == "true"
        include_all_magnitudes = Map.get(params, "includeallmagnitudes", "false") == "true"
        include_arrivals = Map.get(params, "includearrivals", "false") == "true"

        domain = Cache.get_parameter("domain")

        conn =
          conn
          |> put_layout(:none)
          |> put_resp_content_type("application/xml")
          |> send_chunked(:ok)

        escaped_url = Phoenix.Controller.current_url(conn, params) |> String.replace("&", "&amp;")

        chunk(
          conn,
          Phoenix.View.render(Web.FDSNEventView, "query_start.xml", url: escaped_url)
          |> trim_xml()
        )

        for chunk <- get_event_ids_chunks(params, 10) do
          events_query =
            get_events_from_ids(chunk)
            |> Seismic.preload_preferred()
            |> Seismic.preload_distinctive_cities()
            |> Seismic.preload_origins(!(include_all_origins || include_all_magnitudes))
            |> Seismic.preload_magnitudes(!(include_all_origins || include_all_magnitudes))
            |> Seismic.preload_origins_qualities()

          events =
            if include_arrivals do
              Seismic.preload_origins_arrivals(events_query)
            else
              events_query
            end
            |> Repo.all()
            |> sort_events_chunk(params)

          xml =
            Phoenix.View.render(Web.FDSNEventView, "query.xml",
              events: events,
              domain: domain,
              include_all_origins: include_all_origins,
              include_all_magnitudes: include_all_magnitudes,
              include_arrivals: include_arrivals
            )
            |> trim_xml()

          chunk(conn, xml)
        end

        chunk(conn, Phoenix.View.render(Web.FDSNEventView, "query_end.xml", %{}) |> trim_xml())

        conn
    end
  end

  def base(conn, _params) do
    redirect(conn, to: "/en/search")
  end

  def wadl(conn, _params) do
    conn
    |> put_layout(:none)
    |> put_resp_content_type("application/xml")
    |> render("application.wadl", version: @version)
  end

  def catalogs(conn, _params) do
    conn
    |> put_layout(:none)
    |> put_resp_content_type("application/xml")
    |> render("catalog.xml")
  end

  def contributors(conn, _params) do
    conn
    |> put_layout(:none)
    |> put_resp_content_type("application/xml")
    |> render("contributors.xml")
  end

  def version(conn, _params) do
    text(conn, @version)
  end
end

apps/web/lib/web/views/fdsn_event_view.ex
defmodule Web.FDSNEventView do
  use Web, :view
  import Web.Filters
end

apps/web/lib/web/templates/fdsn_event/application.wadl.eex
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<application xmlns="http://wadl.dev.java.net/2009/02">
  <doc title="FDSN event web service <%= @version %>"/>
  <resources base="<%= Routes.fdsn_event_url(@conn, :base) %>">
    <resource path="/">
      <method id="index" name="GET">
        <response>
          <representation mediaType="text/plain"/>
          <representation mediaType="application/xml"/>
        </response>
      </method>
      <resource path="/query">
        <method id="query" name="GET">
          <request>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="starttime" style="query" type="xs:date">
              <doc xml:lang="english" title="limit to events occurring on or after the specified start time" />
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="endtime" style="query" type="xs:date">
              <doc xml:lang="english" title="limit to events occurring on or before the specified end time"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="minlatitude" style="query" type="xs:double">
              <doc xml:lang="english" title="southern boundary"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="maxlatitude" style="query" type="xs:double">
              <doc xml:lang="english" title="northern boundary"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="minlongitude" style="query" type="xs:double">
              <doc xml:lang="english" title="western boundary"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="maxlongitude" style="query" type="xs:double">
              <doc xml:lang="english" title="eastern boundary"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="minmagnitude" style="query" type="xs:double">
              <doc xml:lang="english" title="Limit to events with a magnitude larger than or equal to the specified minimum"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="maxmagnitude" style="query" type="xs:double">
              <doc xml:lang="english" title="Limit to events with a magnitude smaller than or equal to the specified maximum"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="magnitudetype" style="query" type="xs:string">
              <doc xml:lang="english" title="type of Magnitude used to test minimum and maximum limits (case insensitive)" />
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="eventtype" style="query" type="xs:string"> -->
              <doc xml:lang="english" title="Filter events based on their types"/> -->
            </param> -->
            <!-- <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="catalog" style="query" type="xs:string" default="NEIC+PDE"> -->
            <!--   <doc xml:lang="english" title="Specify the catalog from which origins and magnitudes will be retrieved"/> -->
            <!-- </param> -->
            <!-- <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="contributor" style="query" type="xs:string"> -->
            <!--   <doc xml:lang="english" title="Limit to events contributed by a specified contributor"/> -->
            <!-- </param> -->
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="maxdepth" style="query" type="xs:double">
              <doc xml:lang="english" title="Limit to events with depths equal to or less than the specified depth"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="mindepth" style="query" type="xs:double">
              <doc xml:lang="english" title="Limit to events with depths equal to or greater than the specified depth"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="latitude" style="query" type="xs:double" default="0.0">
              <doc xml:lang="english" title="Specify the central latitude point for a radial search"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="longitude" style="query" type="xs:double" default="0.0">
              <doc xml:lang="english" title="Specify the central longitude point for a radial search"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="maxradius" style="query" type="xs:double" default="180.0">
              <doc xml:lang="english" title="Specify maximum distance from the geographic point defined by latitude and longitude"/>
            </param>
            <!-- <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="minradius" style="query" type="xs:double" default="0.0"> -->
            <!--   <doc xml:lang="english" title="Specify minimum distance from the geographic point defined by latitude and longitude"/> -->
            <!-- </param> -->
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="orderby" style="query" type="xs:string" default="time">
              <doc xml:lang="english" title="Specify the ordering of the returned results"/>
              <option value="time">
                <doc xml:lang="english" title="Sort by time, descending"/>
              </option>
              <option value="magnitude">
                <doc xml:lang="english" title="Sort by magnitude, descending"/>
              </option>
              <option value="time-asc">
                <doc xml:lang="english" title="Sort by time, ascending"/>
              </option>
              <option value="magnitude-asc">
                <doc xml:lang="english" title="Sort by magnitude, ascending"/>
              </option>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="updatedafter" style="query" type="xs:date">
              <doc xml:lang="english" title="Limit to events updated after the specified time"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="eventid" style="query" type="xs:string">
              <doc xml:lang="english" title="Retrieve an event based on the unique ID"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="includearrivals" style="query" type="xs:boolean" default="false">
              <doc xml:lang="english" title="Specify if phase arrivals should be included"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="includeallmagnitudes" style="query" type="xs:boolean" default="false">
              <doc xml:lang="english" title="Retrieve all magnitudes for the event, or only the primary magnitude from within the catalog"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="includeallorigins" style="query" type="xs:boolean" default="false">
              <doc xml:lang="english" title="Retrieve all origins or only the primary origin associated with each event in a catalog"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="limit" style="query" type="xs:int">
              <doc xml:lang="english" title="Limit the results to the specified number of events"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="offset" style="query" type="xs:int">
              <doc xml:lang="english" title="Return results starting at the event count specified"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="format" style="query" type="xs:string" default="xml">
              <doc xml:lang="english" title="Specify output format"/>
              <option value="xml" mediaType="application/xml"/>
              <option value="text" mediaType="text/plain"/>
            </param>
            <param xmlns:xs="http://www.w3.org/2001/XMLSchema" name="nodata" style="query" type="xs:int" default="204">
              <doc xml:lang="english" title="Specify which HTML Status code is returned when no data is found."/>
              <option value="204"/>
              <option value="404"/>
            </param>
          </request>
          <response>
            <representation mediaType="text/plain"/>
            <representation mediaType="application/xml"/>
          </response>
        </method>
      </resource>
      <resource path="/version">
        <method id="version" name="GET">
          <response>
            <representation mediaType="text/plain"/>
          </response>
        </method>
      </resource>
      <resource path="/catalogs">
        <method id="catalogs" name="GET">
          <response>
            <representation mediaType="application/xml"/>
          </response>
        </method>
      </resource>
      <resource path="/contributors">
        <method id="contributors" name="GET">
          <response>
            <representation mediaType="application/xml"/>
          </response>
        </method>
      </resource>
    </resource>
  </resources>
</application>

apps/web/lib/web/templates/fdsn_event/catalog.xml.eex
<?xml version="1.0" encoding="UTF-8"?>
<Catalogs>
  <total>1</total>
  <Catalog>BCSF-RENASS</Catalog>
</Catalogs>

apps/web/lib/web/templates/fdsn_event/contributors.xml.eex
<?xml version="1.0" encoding="UTF-8"?>
<Contributors>
  <Contributor>BCSF-RENASS</Contributor>
</Contributors>

apps/web/lib/web/templates/fdsn_event/query.txt.eex
<%= for event <- @events do %>
<%= event.publicid %>|<%= event.preferred_origin.time |> DateTime.to_iso8601() %>|<%= event.preferred_origin.latitude %>|<%= event.preferred_origin.longitude %>|<%= event.preferred_origin.depth %>|<%= event.preferred_origin.author %>|Namazu|<%= event.preferred_origin.agency %>|<%= event.preferred_origin.agency %>|<%= event.preferred_magnitude.magnitude_type %>|<%= event.preferred_magnitude.magnitude %>|<%= event.preferred_magnitude.author %>|<%= Namazu.Helpers.event_description(event) %> (<%= event.zone.name %>)|<%= event.event_type |> Namazu.Seismic.Event.namazu_to_quakeml_event_type() %><% end %>

apps/web/lib/web/templates/fdsn_event/query_end.xml.eex
</eventParameters>
</q:quakeml>

apps/web/lib/web/templates/fdsn_event/query_start.xml.eex
<?xml version="1.0" encoding="UTF-8"?>
<q:quakeml xmlns:q="http://quakeml.org/xmlns/quakeml/1.2" xmlns="http://quakeml.org/xmlns/bed/1.2" xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance" xsi:schemaLocation="http://quakeml.org/schema/xsd http://quakeml.org/schema/xsd/QuakeML-1.2.xsd">
  <eventParameters publicID="smi:<%= @url %>">